// Central budget category icon registry (single source of truth).
// The database stores only the stable kebab-case identifier (never React
// component names, never SVG markup). Every consumer - category manager,
// subcategory dropdown, expense form/table, dashboard, reports - resolves
// through getBudgetCategoryIcon().
import {
  AppWindow,
  AirVent,
  BatteryCharging,
  Blocks,
  Briefcase,
  BrickWall,
  Building,
  Cable,
  Car,
  Circle,
  CircleDot,
  ClipboardList,
  Cog,
  Columns3,
  Container,
  DoorClosed,
  DoorOpen,
  Drill,
  Droplet,
  Droplets,
  Fan,
  Fence,
  FileCheck,
  FileSearch,
  Flame,
  Forklift,
  Frame,
  Gauge,
  Grid2x2,
  Hammer,
  Handshake,
  HardHat,
  Heater,
  Key,
  Lamp,
  Landmark,
  Layers,
  Lightbulb,
  Lock,
  Megaphone,
  Package,
  Paintbrush,
  PaintBucket,
  PaintRoller,
  Pipette,
  Plane,
  Plug,
  PlugZap,
  Power,
  Receipt,
  Rows3,
  Ruler,
  DraftingCompass,
  Scale,
  Settings,
  Shapes,
  ShowerHead,
  ShieldCheck,
  Siren,
  Snowflake,
  Thermometer,
  Toilet,
  ToggleLeft,
  Tractor,
  TrafficCone,
  Trash2,
  Truck,
  Ban,
  Users,
  WashingMachine,
  Waves,
  Wind,
  Wrench,
  Zap,
} from 'lucide-react';

export const DEFAULT_CATEGORY_ICON = 'shapes';

const REGISTRY = {
  'shapes': Shapes,
  'briefcase': Briefcase,
  'users': Users,
  'wrench': Wrench,
  'car': Car,
  'building': Building,
  'megaphone': Megaphone,
  'plane': Plane,
  'receipt': Receipt,
  'handshake': Handshake,
  'folder-kanban': ClipboardList,
  'settings': Settings,
  'cog': Cog,
  'gauge': Gauge,
  'ruler': Ruler,
  'drafting-compass': DraftingCompass,
  'hammer': Hammer,
  'hard-hat': HardHat,
  'brick-wall': BrickWall,
  'blocks': Blocks,
  'landmark': Landmark,
  'container': Container,
  'layers': Layers,
  'grid': Grid2x2,
  'rows': Rows3,
  'columns': Columns3,
  'fence': Fence,
  'paint-roller': PaintRoller,
  'paintbrush': Paintbrush,
  'paint-bucket': PaintBucket,
  'zap': Zap,
  'power': Power,
  'cable': Cable,
  'plug': Plug,
  'plug-zap': PlugZap,
  'battery': BatteryCharging,
  'lamp': Lamp,
  'lightbulb': Lightbulb,
  'toggle': ToggleLeft,
  'droplets': Droplets,
  'droplet': Droplet,
  'pipette': Pipette,
  'waves': Waves,
  'shower': ShowerHead,
  'toilet': Toilet,
  'wind': Wind,
  'fan': Fan,
  'air-vent': AirVent,
  'thermometer': Thermometer,
  'snowflake': Snowflake,
  'heater': Heater,
  'flame': Flame,
  'siren': Siren,
  'traffic-cone': TrafficCone,
  'trash': Trash2,
  'truck': Truck,
  'forklift': Forklift,
  'tractor': Tractor,
  'drill': Drill,
  'package': Package,
  'washing-machine': WashingMachine,
  'door-open': DoorOpen,
  'door-closed': DoorClosed,
  'app-window': AppWindow,
  'frame': Frame,
  'lock': Lock,
  'key': Key,
  'shield-check': ShieldCheck,
  'ban': Ban,
  'clipboard-list': ClipboardList,
  'file-check': FileCheck,
  'file-search': FileSearch,
  'scale': Scale,
  'circle-dot': CircleDot,
  'circle': Circle,
};

export const BUDGET_CATEGORY_ICON_IDS = Object.keys(REGISTRY);

export function getBudgetCategoryIcon(id) {
  return REGISTRY[id] || REGISTRY[DEFAULT_CATEGORY_ICON];
}

export function isKnownCategoryIcon(id) {
  return Object.prototype.hasOwnProperty.call(REGISTRY, id);
}
