[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]

[db]
major_version = 15

[auth]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions]
"invite-user" = {}
"invite-client" = {}
"delete-user" = {}
"create-client" = {}
"create-project-request" = {}
"review-project-request" = {}
"send-push" = {}
