-- =============================================================
-- Migration: Central reminder engine + notification retention
--
-- Goal
--   One server-side, idempotent reminder mechanism that evaluates
--   pending reminders hourly (pg_cron) and writes into the existing
--   public.notifications table. Because reminders are ordinary
--   notification rows, they automatically:
--     * appear in the existing Notifications page and bell;
--     * support read/unread, archive/restore and delete;
--     * reuse the existing trg_notification_push -> send-push chain;
--     * reuse the existing centralized type -> destination resolver.
--
-- Reminder types implemented by public.run_reminder_engine():
--   1. event            -> deadline ~24h away, exactly once per event
--   2. project_request  -> non-verified request, every 24h per recipient
--   3. message          -> unread conversation, at most once per hour
--   4. notification_reminder -> unread notifications, at most once/hour
--   5. automatic archival of active notifications by per-user retention
--
-- Idempotency / duplicate prevention
--   Every generated row carries an explicit identity in
--   notifications.reminder_key and a partial UNIQUE index on that
--   column makes re-running the engine a no-op. The key encodes
--   source_type + source_id + recipient + reminder_type + period:
--     event_deadline_v1:<event_id>
--     project_request_v1:<request_id>:<user_id>:<YYYY-MM-DD>
--     message_unread_v1:<receiver_id>:<sender_id>:<YYYYMMDDHH24>
--     notification_unread_v1:<user_id>:<YYYYMMDDHH24>
--   A time-based "already reminded in the last interval" guard keeps
--   repeating reminders at most once per interval even across clock
--   boundaries. Message text is never used for identity.
--
-- Recursion prevention
--   Reminder rows are marked is_reminder = true. The unread-notification
--   reminder source query excludes is_reminder rows, so a reminder can
--   never generate a reminder about itself (no infinite chain).
--
-- Retention semantics (chosen behavior)
--   Automatic retention ARCHIVES (never deletes) currently ACTIVE
--   (archived = false) notifications whose created_at is older than the
--   owner's profiles.notification_retention_days. Manually archived rows
--   are left untouched; manual archive/restore/delete keep working. A row
--   manually restored while still older than the cutoff is re-archived on
--   the next cycle (that is the definition of the retention cutoff).
--   Changing the setting only affects future cycles; no data is destroyed.
--
-- Everything below is additive and idempotent: no table is replaced, no
-- existing policy/trigger/function/column is dropped, and the push trigger
-- is only re-created with two extra title cases (identical otherwise).
-- =============================================================

-- -------------------------------------------------------------
-- 1. Additive notification metadata used by the reminder engine
-- -------------------------------------------------------------
alter table public.notifications
  add column if not exists reminder_key text,
  add column if not exists is_reminder boolean not null default false;

comment on column public.notifications.reminder_key is
  'Explicit reminder identity (source_type:source_id:recipient:type:period). NULL for non-reminder notifications. Unique when set.';
comment on column public.notifications.is_reminder is
  'True when the row was generated by run_reminder_engine(). Excluded from the unread-notification reminder source to prevent recursion.';

-- Hard idempotency: a scheduled job that retries/overlaps can never
-- insert the same reminder twice.
create unique index if not exists notifications_reminder_key_uidx
  on public.notifications (reminder_key)
  where reminder_key is not null;

-- -------------------------------------------------------------
-- 2. Performance indexes for the hourly scans
-- -------------------------------------------------------------
-- Retention scan: active rows per user by age.
create index if not exists notifications_active_created_idx
  on public.notifications (user_id, created_at)
  where archived = false;

-- Unread-notification reminder source (excludes reminder rows).
create index if not exists notifications_unread_source_idx
  on public.notifications (user_id, created_at)
  where archived = false and is_read is not true and is_reminder = false;

-- Recently generated reminders, used by the per-interval guard.
create index if not exists notifications_reminder_recent_idx
  on public.notifications (user_id, created_at)
  where is_reminder = true;

-- Event deadline scan.
create index if not exists events_reminder_due_idx
  on public.events (date, time)
  where archived = false;

-- Non-verified project request scan.
create index if not exists project_requests_reminder_idx
  on public.project_requests (status, created_at);

-- Unread message scan.
create index if not exists messages_unread_reminder_idx
  on public.messages (receiver_id, created_at)
  where is_read is not true;

-- -------------------------------------------------------------
-- 3. Per-user notification retention setting
--    Values: 1 (24h) | 7 (1 week, default) | 30 (1 month)
-- -------------------------------------------------------------
alter table public.profiles
  add column if not exists notification_retention_days integer not null default 7;

alter table public.profiles
  drop constraint if exists profiles_notification_retention_days_check;

alter table public.profiles
  add constraint profiles_notification_retention_days_check
  check (notification_retention_days in (1, 7, 30));

comment on column public.profiles.notification_retention_days is
  'Days a notification stays active before automatic archival (1=24h, 7=1 week, 30=1 month). Default 7.';

-- -------------------------------------------------------------
-- 4. Central reminder engine
--    Deterministic and testable: pass p_now to simulate a run instant.
--    SECURITY DEFINER so pg_cron (and service_role) can write for every
--    user while bypassing RLS; returns a small jsonb summary.
-- -------------------------------------------------------------
create or replace function public.run_reminder_engine(p_now timestamptz default now())
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_now_ts                 timestamp;
  v_now_bucket             text;
  v_now_day                text;
  v_event_reminders        integer := 0;
  v_request_reminders      integer := 0;
  v_message_reminders      integer := 0;
  v_notification_reminders integer := 0;
  v_auto_archived          integer := 0;
begin
  -- Deadlines are stored as timezone-less date + time; compare against the
  -- database wall clock (UTC) so the hourly cadence stays deterministic.
  v_now_ts     := p_now at time zone 'UTC';
  v_now_bucket := to_char(v_now_ts, 'YYYYMMDDHH24');
  v_now_day    := to_char(v_now_ts, 'YYYY-MM-DD');

  -- -----------------------------------------------------------
  -- 4.1 EVENT DEADLINE REMINDERS
  --     Fires once, on the first hourly run that sees the event
  --     within ~24h of its deadline and still in the future.
  --     Recipient: the event owner. Archived events are excluded.
  -- -----------------------------------------------------------
  insert into public.notifications
    (user_id, type, message, url, is_read, archived, is_reminder, reminder_key, created_at)
  select
    e.user_id,
    'event',
    'Reminder: ' || e.title || ' is due tomorrow at ' || to_char(e.time, 'HH24:MI') || '.',
    '/calendar',
    false, false, true,
    'event_deadline_v1:' || e.id::text,
    p_now
  from public.events e
  where e.archived = false
    and e.date is not null
    and e.time is not null
    and e.user_id is not null
    and (e.date + e.time) > v_now_ts
    and (e.date + e.time) <= v_now_ts + interval '24 hours'
  on conflict (reminder_key) where reminder_key is not null do nothing;
  get diagnostics v_event_reminders = row_count;

  -- -----------------------------------------------------------
  -- 4.2 NON-VERIFIED PROJECT REQUEST REMINDERS
  --     "Non-verified" = status in ('pending','verification') per the
  --     existing review-project-request workflow (validated/rejected end
  --     it). Recipients: super admins (same audience as the producer),
  --     routed to Request Management by the centralized resolver.
  --     One reminder per recipient per day, starting after 24h.
  -- -----------------------------------------------------------
  insert into public.notifications
    (user_id, type, message, url, is_read, archived, is_reminder, reminder_key, created_at)
  select
    sa.id,
    'project_request',
    'Reminder: project request "' || pr.project_name || '" is still awaiting verification.',
    '/requests?view=management',
    false, false, true,
    'project_request_v1:' || pr.id::text || ':' || sa.id::text || ':' || v_now_day,
    p_now
  from public.project_requests pr
  cross join public.profiles sa
  join public.roles r on r.id = sa.role_id
  where r.name = 'super_admin'
    and pr.status in ('pending', 'verification')
    and coalesce(pr.archived, false) = false
    and pr.created_at <= p_now - interval '24 hours'
    and not exists (
      select 1
      from public.notifications prev
      where prev.is_reminder = true
        and prev.user_id = sa.id
        and prev.created_at > p_now - interval '24 hours'
        and prev.reminder_key like 'project\_request\_v1:%' escape '\'
    )
  on conflict (reminder_key) where reminder_key is not null do nothing;
  get diagnostics v_request_reminders = row_count;

  -- -----------------------------------------------------------
  -- 4.3 UNREAD MESSAGE REMINDERS
  --     One reminder per unread conversation, at most once per hour,
  --     only after the newest eligible message is at least one hour old.
  --     Stops automatically once the receiver reads (is_read) or the
  --     messages are deleted. Deep-links to the conversation.
  -- -----------------------------------------------------------
  insert into public.notifications
    (user_id, type, message, url, is_read, archived, is_reminder, reminder_key, created_at)
  select
    m.receiver_id,
    'message',
    'Reminder: you have ' || count(*) || ' unread message'
      || case when count(*) > 1 then 's' else '' end
      || ' from ' || coalesce(p.full_name, p.email, 'a colleague') || '.',
    '/messages?user=' || m.sender_id::text,
    false, false, true,
    'message_unread_v1:' || m.receiver_id::text || ':' || m.sender_id::text || ':' || v_now_bucket,
    p_now
  from public.messages m
  left join public.profiles p on p.id = m.sender_id
  where m.is_read is not true
    and m.created_at <= p_now - interval '1 hour'
    and not exists (
      select 1
      from public.notifications prev
      where prev.is_reminder = true
        and prev.user_id = m.receiver_id
        and prev.created_at > p_now - interval '1 hour'
        and prev.reminder_key like 'message\_unread\_v1:%' escape '\'
    )
  group by m.receiver_id, m.sender_id, p.full_name, p.email
  on conflict (reminder_key) where reminder_key is not null do nothing;
  get diagnostics v_message_reminders = row_count;

  -- -----------------------------------------------------------
  -- 4.4 UNREAD NOTIFICATION REMINDERS
  --     At most once per hour per user. Excludes reminder rows
  --     (is_reminder) to prevent recursive reminder chains and excludes
  --     archived rows. Stops once the originals are read.
  -- -----------------------------------------------------------
  insert into public.notifications
    (user_id, type, message, url, is_read, archived, is_reminder, reminder_key, created_at)
  select
    n.user_id,
    'notification_reminder',
    'Reminder: you have ' || count(*) || ' unread notification'
      || case when count(*) > 1 then 's' else '' end || '.',
    '/notifications',
    false, false, true,
    'notification_unread_v1:' || n.user_id::text || ':' || v_now_bucket,
    p_now
  from public.notifications n
  where n.user_id is not null
    and n.archived = false
    and n.is_read is not true
    and n.is_reminder = false
    and n.created_at <= p_now - interval '1 hour'
    and not exists (
      select 1
      from public.notifications prev
      where prev.is_reminder = true
        and prev.user_id = n.user_id
        and prev.created_at > p_now - interval '1 hour'
        and prev.reminder_key like 'notification\_unread\_v1:%' escape '\'
    )
  group by n.user_id
  on conflict (reminder_key) where reminder_key is not null do nothing;
  get diagnostics v_notification_reminders = row_count;

  -- -----------------------------------------------------------
  -- 4.5 AUTOMATIC ARCHIVAL BY RETENTION
  --     Archives (never deletes) active notifications older than the
  --     owner's selected retention. Manual archive is already archived,
  --     so it is untouched.
  -- -----------------------------------------------------------
  update public.notifications n
     set archived = true
    from public.profiles p
   where p.id = n.user_id
     and n.archived = false
     and n.created_at < p_now - make_interval(days => p.notification_retention_days);
  get diagnostics v_auto_archived = row_count;

  return jsonb_build_object(
    'ran_at',                   p_now,
    'event_reminders',          v_event_reminders,
    'project_request_reminders', v_request_reminders,
    'message_reminders',        v_message_reminders,
    'notification_reminders',   v_notification_reminders,
    'auto_archived',            v_auto_archived
  );
end;
$$;

revoke all on function public.run_reminder_engine(timestamptz) from public;
grant execute on function public.run_reminder_engine(timestamptz) to service_role;

-- -------------------------------------------------------------
-- 5. Push titles for the new reminder types
--    Same trigger function as 20260922000000 (Vault-backed URL + token,
--    graceful skip, observability logs); only two title cases added.
--    trg_notification_push itself is left untouched.
-- -------------------------------------------------------------
create or replace function public.handle_new_notification_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_edge_url   text;
  v_push_token text;
  v_title      text;
  v_payload    jsonb;
  v_headers    jsonb;
begin
  if new.user_id is null then
    return new;
  end if;

  select decrypted_secret into v_edge_url
    from vault.decrypted_secrets
   where name = 'notifications_edge_function_url'
   order by updated_at desc
   limit 1;

  select decrypted_secret into v_push_token
    from vault.decrypted_secrets
   where name = 'notifications_internal_push_token'
   order by updated_at desc
   limit 1;

  if v_edge_url is null or v_push_token is null then
    raise log
      'push: delivery skipped for notification % (user %) — edge_url_present=%, token_present=%',
      new.id,
      new.user_id,
      v_edge_url is not null,
      v_push_token is not null;
    return new;
  end if;

  v_title := case coalesce(new.type, '')
    when 'message'          then 'New message'
    when 'project_request'  then 'New project request'
    when 'project_update'   then 'Project update'
    when 'project_assignment' then 'Project assignment'
    when 'role_update'      then 'Role update'
    when 'status_change'    then 'Status change'
    when 'team_assignment'  then 'Team assignment'
    when 'invoice_change'   then 'Invoice update'
    when 'permit_expiry'    then 'Permit expiry'
    when 'deadline_alert'   then 'Deadline alert'
    when 'event'            then 'Event reminder'
    when 'notification_reminder' then 'Unread notifications'
    else 'Geometra'
  end;

  v_payload := jsonb_build_object(
    'title',           v_title,
    'body',            new.message,
    'receiver_id',     new.user_id,
    'type',            new.type,
    'url',             new.url,
    'notification_id', new.id
  );

  v_headers := jsonb_build_object(
    'Content-Type',  'application/json',
    'x-push-token',  v_push_token
  );

  perform net.http_post(
    url                  := v_edge_url,
    body                 := v_payload,
    headers              := v_headers,
    timeout_milliseconds := 10000
  );

  raise log 'push: queued delivery for notification % (user %)',
    new.id,
    new.user_id;

  return new;
end;
$$;

revoke execute on function public.handle_new_notification_push() from public, anon, authenticated;

-- -------------------------------------------------------------
-- 6. Hourly schedule (server-side, works while every browser is closed)
--    pg_cron runs the engine as the job owner; the engine is SECURITY
--    DEFINER. Scheduling is idempotent: any previous job with the same
--    name is replaced. If pg_cron is unavailable the migration still
--    succeeds and logs a warning instead of failing the deploy.
-- -------------------------------------------------------------
do $$
begin
  begin
    execute 'create extension if not exists pg_cron';
  exception when others then
    raise log 'reminder engine: pg_cron extension unavailable (%)', sqlerrm;
  end;

  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    begin
      if exists (select 1 from cron.job where jobname = 'geometra-reminder-engine') then
        perform cron.unschedule('geometra-reminder-engine');
      end if;

      perform cron.schedule(
        'geometra-reminder-engine',
        '0 * * * *',
        $cron$select public.run_reminder_engine();$cron$
      );

      raise log 'reminder engine: pg_cron job "geometra-reminder-engine" scheduled hourly';
    exception when others then
      raise log 'reminder engine: could not schedule pg_cron job (%)', sqlerrm;
    end;
  end if;
end
$$;

notify pgrst, 'reload schema';
